version: '3'
services:
  server:
    image: centos:7

  php:
    image: php:7.2-fpm
    volumes:
    - マウントしたいローカルディレクトリ:/var/www/html
    - ./php/www.conf:/etc/php-fpm.d/www.conf

  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - mysql
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8080:80
